"""Generate model-facing definitions from the canonical tier descriptions; no API calls."""

import argparse
import json
from pathlib import Path

DATA = Path(__file__).resolve().parents[1] / "data"


def build(taxonomy):
    nodes = taxonomy["nodes"]
    index = {n["id"]: n for n in nodes}
    if len(index) != len(nodes):
        raise ValueError("Duplicate category ID")
    reserved = {"insufficient_evidence", "outside_taxonomy"}
    if reserved.intersection(index):
        raise ValueError("Category IDs must not use reserved abstention names")
    for node in nodes:
        tier = node["tier"]
        parent = index.get(node["parent_id"])
        if tier not in (1, 2, 3) or not node["description"].strip():
            raise ValueError("Invalid tier or empty description: " + node["id"])
        if tier == 1:
            if node["parent_id"] is not None:
                raise ValueError("Tier 1 must have no parent")
        elif parent is None or parent["tier"] != tier - 1:
            raise ValueError("Missing or wrong-tier parent: " + node["id"])
    codes = [n.get("industry_code") for n in nodes if n["tier"] == 3]
    if any(
        not isinstance(c, str) or len(c) != 6 or not c.isascii() or not c.isdigit() for c in codes
    ):
        raise ValueError("Every leaf requires a six-digit string industry placeholder")
    if len(set(codes)) != len(codes):
        raise ValueError("This demo requires a unique placeholder per leaf")
    paths = []
    for leaf in nodes:
        if leaf["tier"] != 3:
            continue
        second = index[leaf["parent_id"]]
        chain = [index[second["parent_id"]], second, leaf]
        title = " → ".join(n["name"] for n in chain)
        conditions = [
            dict(tier=n["tier"], category_id=n["id"], description=n["description"]) for n in chain
        ]
        exclusions = [
            dict(tier=n["tier"], category_id=n["id"], description=n["exclusions"])
            for n in chain
            if n.get("exclusions")
        ]
        definition = title + "\nAll of these conditions must hold:\n"
        definition += "\n".join(
            "Tier %s (%s): %s" % (n["tier"], n["name"], n["description"]) for n in chain
        )
        if exclusions:
            definition += "\nInherited exclusions:\n" + "\n".join(
                "- " + e["description"] for e in exclusions
            )
        definition += "\nClassification policy: " + taxonomy["classification_policy"]
        paths.append(
            dict(
                leaf_id=leaf["id"],
                path_ids=[n["id"] for n in chain],
                path_name=title,
                required_conditions=conditions,
                inherited_exclusions=exclusions,
                combined_definition=definition,
                industry_code=leaf["industry_code"],
                industry_code_status=leaf["industry_code_status"],
            )
        )
    return dict(taxonomy_version=taxonomy["version"], generated_from="taxonomy.json", paths=paths)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=DATA)
    args = parser.parse_args()
    data = args.data_dir
    result = build(json.loads((data / "taxonomy.json").read_text()))
    (data / "path_definitions.json").write_text(
        json.dumps(result, indent=2, ensure_ascii=False) + "\n"
    )
    overview = [
        "# Generated industry path definitions",
        "",
        "Generated from `taxonomy.json`. Edit the source descriptions, then rerun `python scripts/build_industry_definitions.py --data-dir PATH_TO_THIS_DATASET`. Do not edit this file directly.",
        "",
    ]
    for path in result["paths"]:
        overview += [
            "## " + path["path_name"],
            "",
            path["combined_definition"],
            "",
            "Fixed industry code: `"
            + path["industry_code"]
            + "` (placeholder, not an official code).",
            "",
        ]
    (data / "PATH_DEFINITIONS.md").write_text("\n".join(overview))
    print("Generated %d complete path definitions." % len(result["paths"]))


if __name__ == "__main__":
    main()
